code --install-extension adpyke.codesnap
code --install-extension ahmadalli.vscode-nginx-conf
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-rename-tag
code --install-extension formulahendry.code-runner
code --install-extension icrawl.discord-vscode
code --install-extension mrmlnc.vscode-scss
code --install-extension ms-azuretools.vscode-docker
code --install-extension PKief.material-icon-theme
code --install-extension raynigon.nginx-formatter
code --install-extension redhat.vscode-yaml
code --install-extension ritwickdey.LiveServer
code --install-extension rust-lang.rust
code --install-extension sleistner.vscode-fileutils
code --install-extension statiolake.vscode-rustfmt
code --install-extension vscodevim.vim
code --install-extension WakaTime.vscode-wakatime
code --install-extension yzhang.markdown-all-in-one
code --install-extension zhuangtongfa.material-theme
