tap "homebrew/bundle"
tap "homebrew/core"
# Yet another cross-platform graphical process/system monitor
brew "bottom"
# Isolated development environments using Docker
brew "docker-compose"
# Command-line fuzzy finder written in Go
brew "fzf"
# GNU compiler collection
brew "gcc"
# NCurses Disk Usage
brew "ncdu"
# Manage multiple Node.js versions
brew "nvm"
# Build better apps by developing and testing code directly in Kubernetes
brew "okteto"
# Shell extension to navigate your filesystem faster
brew "zoxide"
